[theme]
primaryColor = "#ff66a3"          # A vibrant pink for buttons and highlights
backgroundColor = "#ffe6f2"       # A soft pink background
secondaryBackgroundColor = "#ffffff"  # Clean white for cards or tables
textColor = "#333333"             # Dark text for readability
